---
- name: Destroy | VPC | AWSe
  debug:
    msg: "Destroy VPC Endpoint service triggered"
  tags: vpc

- name: Get all endpoints with specific filters
  community.aws.ec2_vpc_endpoint_info:
    query: endpoints
    region: "{{ vpc_region }}"
    filters:
      vpc-id:
        - "{{ vpc_id }}"
      vpc-endpoint-state:
        - available
        - pending
  register: res_vpce

- name: Delete newly created vpc endpoint
  ec2_vpc_endpoint:
    state: absent
    vpc_endpoint_id: "{{ item.vpc_endpoint_id }}"
    region: "{{ vpc_region }}"
  with_items: "{{ res_vpce.vpc_endpoints }}"

#- name: Destroy | VPC | VPCe Services
#  ec2_vpc_endpoint:
#    state: absent
#    region: "{{ vpc_region }}"
#    vpc_id: "{{ vpc_id }}"
#    service: "{{ item }}"
#  with_items:
#    - "com.amazonaws.{{ vpc_region }}.s3"

