- name: InstallerConfig | Create the install dir
  file:
    state: directory
    path: "{{ install_dir }}"
    recurse: yes

- name: InstallerConfig | Check if metadata.json exists
  stat:
    path: "{{ install_dir }}/metadata.json"
  register: st_out

- name: InstallerConfig | Check if pull secret file from env var CONFIG_PULL_SECRET_FILE exists
  stat:
    path: "{{ config_pullSecret_file }}"
  register: ps_out

- name: InstallerConfig | Fail when pull secret file is not present
  debug:
    msg: "CONFIG_PULL_SECRET_FILE env var was not found. Please set it with pull-secret file path"
  failed_when: not(ps_out.stat.exists)

- name: InstallerConfig | Create the install config
  template:
    src: ocp-install-config.yaml.j2
    dest: "{{ install_dir }}/install-config.yaml"
  when: not(st_out.stat.exists)

- name: InstallerConfig | Backup the rendered install config
  template:
    src: ocp-install-config.yaml.j2
    dest: "{{ install_dir }}/install-config-bkp.yaml"
  when: not(st_out.stat.exists)

- name: InstallerConfig | Create manifests
  shell: |
    {{ bin_openshift_install }} create manifests --dir {{ install_dir }}
  when: not(st_out.stat.exists)

- name: InstallerConfig | Remove Cluster/Machine API manifests for UPI
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_master-machines-1.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_master-machines-2.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_master-machines-3.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-1.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-2.yaml"
    - "{{ install_dir }}/openshift/99_openshift-cluster-api_worker-machineset-3.yaml"
  when: not(st_out.stat.exists)

- name: InstallerConfig | Create ignition configs
  shell: |
    {{ bin_openshift_install }} create ignition-configs --dir {{ install_dir }}
  when: not(st_out.stat.exists)

