all:
  hosts:
    localhost:
      supported_providers: ["aws"]
      supported_platforms: ["aws", "none"]
      ansible_connection: local
      ansible_python_interpreter: $VIRTUAL_ENV/bin/python3
  children:
    cloud:
      hosts:
        aws:
          ansible_host: localhost
          ansible_connection: local
