site_name: "@mtulio labs | notes"
site_url: https://mtulio.net
site_author: 'Marco Braga'
site_description: >-
  Marco Braga | Playground
repo_url: https://github.com/mtulio/mtulio.labs
edit_uri: edit/main/docs/
docs_dir: docs
dev_addr: 127.0.0.1:8080

theme:
  # https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      # primary: red
      # accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    #- navigation.indexes

    # integrate menus
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - diagrams:
      file_extension: ".diagram.py"
      max_workers: 5

markdown_extensions:
  # - toc:
  #     permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  # enable mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
      provider: google
      property: G-HR0NQWHH1T
  # consent:
  #     title: Cookie consent
  #     description: >
  #         We use cookies to recognize your repeated visits and preferences, as well
  #         as to measure the effectiveness of our documentation and whether users
  #         find what they're searching for. With your consent, you're helping us to
  #         make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtulio
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mtulio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mtuliorbraga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mtuliorbraga/

nav:
  - Home:
    - index.md
    # - about.md
    # - tools.md
  - Guides:
      - Home: playbooks/README.md
      - OpenShift API:
        - Replace Kube-API AWS NLB target type: playbooks/openshift/replace-nlb-tg-k8sapi.md

      - OpenShift Node/Machine operations:
        - Machine resize: playbooks/openshift/resize-machines.md
        - Machine resize plugin: playbooks/openshift/resize-machines-plugin.md
        - Using Instance Disks for containers' ephemeral storage: playbooks/openshift/ocp-aws-disk-ephemeral.md
        - AWS - Create EC2 manually: playbooks/openshift/ocp-aws-create-compute.md

      - OpenShift Installing:
        - Installing OpenShift with STS quickly on AWS: playbooks/openshift/ocp-aws-cco-sts-install-quickly.md
        - Installing OpenShift on Alibaba Cloud in existing VPC: playbooks/openshift/ocp-installing-alibabacloud.md
        - Installing OpenShift on Alibaba Cloud in restricted environment [draft]: playbooks/openshift/ocp-installing-alibabacloud.md
        - Installing Hypershift on AWS with STS (draft/unfinished): playbooks/openshift/hypershift-install-sts.md
        - Installing single node (SNO) on AWS [draft]: playbooks/openshift/ocp-aws-sno-install.md

      - OpenShift on AWS with STS:
        - Articles: playbooks/openshift/ocp-aws-cco-oidc.md
        - Hacking CCO manual mode: playbooks/openshift/ocp-aws-cco-run-instance.md
        - Simulate CredentialsRequests permissions: playbooks/openshift/ocp-aws-cco-simulate-policy.md
        - Troubleshooting RunInstance Error: playbooks/openshift/ocp-aws-cco-sts-runinstance-error-kcs.md
        - Troubleshooting InvalidIdentityToken: playbooks/openshift/ocp-installing-aws-sts-oidc-private-bucket.md
        - Review CredentialsRequests provided by CCO: playbooks/openshift/ocp-cco-review-sts-secrets.md

      - OpenShift Dev:
        - Build components: playbooks/openshift/dev-build-components.md
        - Create custom release: playbooks/openshift/dev-custom-release.md
        - Get Credentials with CI Registry: playbooks/openshift/install-credentials-with-ci.md
        - Extract openshift-tests utility: playbooks/openshift/dev-extract-openshift-tests.md

      #- OpenShift in AWS:

  - Notes:
    - Home: notes/README.md
    - automation:
      - ansible: notes/automation/ansible.md
      - rundeck: notes/automation/rundeck.md

    - cloud:
      # AWS
      - aws-cli: notes/cloud/aws-cli.md
      - aws-ec2: notes/cloud/aws-ec2.md
      - aws-ecr: notes/cloud/aws-ecr.md
      - aws-eks: notes/cloud/aws-eks.md
      - aws-iam: notes/cloud/aws-iam.md
      - aws-instances: notes/cloud/aws-instances.md
      - aws-localstack: notes/cloud/aws-localstack.md
      - aws-monit-quotas: notes/cloud/aws-monitoring-quotas.md
      - aws-network: notes/cloud/aws-network.md
      - aws-nlb: notes/cloud/aws-nlb.md
      - aws-s3: notes/cloud/aws-s3.md
      - aws-sts: notes/cloud/aws-sts.md
      - aws-zones: notes/cloud/aws-zones.md
      # Azure
      - azure-monitor: notes/cloud/az-montior.md
      - azure-ha: notes/cloud/azure-ha.md
      - azure-network: notes/cloud/azure-network.md
      # AlibabaCloud
      - aliyun-cli: notes/cloud/aliyun-cli.md
      - aliyun-cli-disks: notes/cloud/aliyun-cli-disks.md
      - aliyun-ecs: notes/cloud/aliyun-ecs.md
      - aliyun-ecs: notes/cloud/aliyun-kms.md
      - aliyun-oss: notes/cloud/aliyun-oss.md
      - aliyun-ram: notes/cloud/aliyun-ram.md
      - aliyun-resourcemanager: notes/cloud/aliyun-resourcemanager.md
      - aliyun-slb: notes/cloud/aliyun-slb.md
      - aliyun-vpc: notes/cloud/aliyun-vpc.md
      # General
      - cloud-init: notes/cloud/cloud-init.md

    - container:
      - Kubernetes: 
        #- k8s: notes/container/kubernetes.md
        - K8S: notes/container/k8s/README.md
        - oc-patch: notes/container/k8s/kubectl-patch.md
        - oc-plugins: notes/container/k8s/kubectl-patch.md
      - OpenShift:
        - OpenShift: notes/container/openshift/README.md
        - pipelines: notes/container/openshift/pipelines.md
        - CVO: notes/container/openshift/cvo.md
        - Custom Image: notes/container/openshift/CVO.md
        - ocp-user-monit: notes/container/openshift/ocp-user-monit.md
        - ocp-idp: notes/container/openshift/ocp-idp.md
        - ROSA: notes/container/openshift/rosa-references.md
      - alpine: notes/container/alpine.md

    - db:
      - elasticsearch: notes/db/elasticsearch/README.md
      - MongoDB: notes/db/mongo.md
      - MongoDB-deployment: notes/db/MongoDB-deployment.md
      - MySQL: notes/db/mysql.md
      - Redis: notes/db/redis.md

    - dev:
      - git: notes/development/git.md
      - lang_c: notes/development/lang_c.md
      - lang_go: notes/development/lang_go.md
      - python-basic: notes/development/python-basic.md
      - python-install: notes/development/python-install.md
      - python-lambda: notes/development/python-lambda.md
      - python-pypi: notes/development/python-pypi.md
      - python-tips: notes/development/python-tips.md
      - tool-jq: notes/development/tool-jq.md
      - yaml: notes/development/yaml.md
      - js-md: notes/development/js-md.md

    - Linux:
      - cmd-find: notes/linux/cmd-find.md
      - curl: notes/linux/curl.md
      - firewall-cmd: notes/linux/firewall-cmd.md
      - gnome: notes/linux/gnome.md
      - log_parser: notes/linux/log_parser.md
      - network_knife: notes/linux/network_knife.md
      - openssl: notes/linux/openssl.md
      - shell: notes/linux/shell.md
      - ssh: notes/linux/ssh.md
      - systemd: notes/linux/systemd.md
      - vdo: notes/linux/vdo.md
      - vi: notes/linux/vi.md
      - wsl: notes/linux/wsl.md

    - Observability:
      - graylog: notes/observability/graylog.md
      - netdata: notes/observability/netdata.md
      - prometheus: notes/observability/prometheus.md

    - Tools:
      - Wireshark: notes/tools/wireshark.md
    
    - RaspberryPi:
      - WiFi: notes/rpi/wifi.md

    - References: notes/references.md

    - Templates:
      - mkdocs-tabs: notes/templates/mkdocs-tabs.md
      - notes/templates/mkdocs-Admonitions.md

  - Articles:
    - Home: articles/README.md
    - OpenShift OIDC:
      - Deep Dive into OpenShift IdP OIDC: articles/ocp-idp-aws-oidc.md
      - Use CloudFront for public URL of OIDC on OpenShift: articles/ocp-idp-aws-oidc-s3-pvt-cfn.md
    - OpenShift in the Edge:
      - "Day-2: Extend OpenShift to the edge with AWS Local Zones": articles/ocp-aws-local-zones-day-2.md
      - "Day-0: Install OpenShift with compute on the edge using AWS Local Zones": articles/ocp-aws-local-zones-day-0.md
      - Use oc plugin to install OpenShift with compute on the edge using AWS Local Zones: articles/ocp-aws-local-zones-day-0-plugin.md
    - OpenShift Ingress:
      - WIP|Using multiple AWS ALB Operator on OpenShift: articles/ocp-aws-local-zones-app-alb.md

  - Open Learning:
      - Home: learning/README.md
      - Workshops: learning/workshops.md
      - Trainings: learning/trainings.md
