site_name: "@mtulio labs | notes"
site_url: https://notes.mtulio.eng.br
site_author: 'Marco Braga'
site_description: >-
  Marco Braga | Playground
repo_url: https://github.com/mtulio/mtulio.labs

docs_dir: docs

# theme:
#   name: cerulean
#   nav_style: dark

theme:
  # https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      # primary: red
      # accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top

    # integrate menus
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

  font:
    text: Roboto
    code: Roboto Mono
  

# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtulio
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mtulio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mtuliorbraga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mtuliorbraga/

markdown_extensions:
  # - toc:
  #     permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  

nav:
  - Home:
    - index.md
    - about.md
    - tools.md
  - Runbooks:
      - Home: playbooks/README.md
      - OpenShift:
        - Machine resize: playbooks/openshift/resize-machines.md
        - Machine resize plugin: playbooks/openshift/resize-machines-plugin.md
        - Replace Kube-API AWS NLB target type: playbooks/openshift/replace-nlb-tg-k8sapi.md
      - OpenShift Dev:
        - Build components: playbooks/openshift/dev-build-components.md
        - Create custom release: playbooks/openshift/dev-custom-release.md
        - Get Credentials with CI Registry: playbooks/openshift/install-credentials-with-ci.md

  - Notes:
    - Home: notes/README.md
    - automation:
      - ansible: notes/automation/ansible.md
      - rundeck: notes/automation/rundeck.md

    - cloud:
      - aws-cli: notes/cloud/aws-cli.md
      - aws-ec2: notes/cloud/aws-ec2.md
      - aws-iam: notes/cloud/aws-iam.md
      - aws-instances: notes/cloud/aws-instances.md
      - aws-monitoring: notes/cloud/aws-monitoring.md
      - aws-network: notes/cloud/aws-network.md
      - aws-nlb: notes/cloud/aws-nlb.md
      - aws-s3: notes/cloud/aws-s3.md
      - azure-ha: notes/cloud/azure-ha.md
      - aliyun-cli: notes/cloud/aliyun-cli.md
      - aliyun-ecs: notes/cloud/aliyun-ecs.md
      - aliyun-oss: notes/cloud/aliyun-oss.md
      - aliyun-ram: notes/cloud/aliyun-ram.md
      - aliyun-vpc: notes/cloud/aliyun-vpc.md
      - cloud-init: notes/cloud/cloud-init.md

    - container:
      - Kubernetes: 
        #- k8s: notes/container/kubernetes.md
        - K8S: notes/container/k8s/README.md
        - oc-patch: notes/container/k8s/kubectl-patch.md
        - oc-plugins: notes/container/k8s/kubectl-patch.md
      - OpenShift:
        - OpenShift: notes/container/openshift/README.md
        - pipelines: notes/container/openshift/pipelines.md
        - CVO: notes/container/openshift/cvo.md
        - Custom Image: notes/container/openshift/CVO.md

    - db:
      - elasticsearch: notes/db/elasticsearch/README.md
      - MongoDB: notes/db/mongo.md
      - MongoDB-deployment: notes/db/MongoDB-deployment.md
      - MySQL: notes/db/mysql.md
      - Redis: notes/db/redis.md

    - dev:
      - git: notes/development/git.md
      - lang_c: notes/development/lang_c.md
      - lang_go: notes/development/lang_go.md
      - python-basic: notes/development/python-basic.md
      - python-install: notes/development/python-install.md
      - python-lambda: notes/development/python-lambda.md
      - python-pypi: notes/development/python-pypi.md
      - python-tips: notes/development/python-tips.md
      - tool-jq: notes/development/tool-jq.md
      - yaml: notes/development/yaml.md

    - Linux:
      - cmd-find: notes/linux/cmd-find.md
      - curl: notes/linux/curl.md
      - firewall-cmd: notes/linux/firewall-cmd.md
      - gnome: notes/linux/gnome.md
      - log_parser: notes/linux/log_parser.md
      - network_knife: notes/linux/network_knife.md
      - openssl: notes/linux/openssl.md
      - shell: notes/linux/shell.md
      - ssh: notes/linux/ssh.md
      - systemd: notes/linux/systemd.md
      - vdo: notes/linux/vdo.md
      - vi: notes/linux/vi.md
      - wsl: notes/linux/wsl.md

    - Observability:
      - graylog: notes/observability/graylog.md
      - netdata: notes/observability/netdata.md
      - prometheus: notes/observability/prometheus.md

    - Tools:
      - Wireshark: notes/tools/wireshark.md
    
    - RaspberryPi:
      - WiFi: notes/rpi/wifi.md

    - References: notes/references.md

    - Templates:
      - mkdocs-tabs: notes/templates/mkdocs-tabs.md
      - notes/templates/mkdocs-Admonitions.md

  - Articles:
    - Home: articles/README.md
    - Articles: articles/index.md

  - Open Learning:
      - Home: learning/README.md
      - Workshops: learning/workshops.md
