site_name: "@mtulio notes"
site_url: https://notes.mtulio.eng.br
site_author: 'Marco Braga'
site_description: >-
  Marco Braga public notes.
repo_url: https://github.com/mtulio/notebooks

docs_dir: root

# theme:
#   name: cerulean
#   nav_style: dark

theme:
  # https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
  name: material
  palette:
    - scheme: slate
      # primary: red
      # accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top

    # integrate menus
    #- toc.integrate
    - search.highlight
    - search.share
    - search.suggest

  font:
    text: Roboto
    code: Roboto Mono

# plugins:
#   - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtulio
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mtulio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mtuliorbraga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mtuliorbraga/

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - automation:
    - ansible: notes/automation/ansible.md
    - rundeck: notes/automation/rundeck.md

  - cloud:
    - aws-cli: notes/cloud/aws-cli.md
    - aws-iam: notes/cloud/aws-iam.md
    - aws-network: notes/cloud/aws-network.md
    - cloud-init: notes/cloud/cloud-init.md

  - container:
    - kubernetes: notes/container/kubernetes.md
    - openshift:
      - pipelines: notes/container/openshift/pipelines.md

  - db:
    - elasticsearch: notes/db/elasticsearch/README.md
    - MongoDB: notes/db/mongo.md
    - MongoDB-deployment: notes/db/MongoDB-deployment.md
    - MySQL: notes/db/mysql.md
    - Redis: notes/db/redis.md

  - dev:
    - git: notes/development/git.md
    - lang_c: notes/development/lang_c.md
    - lang_go: notes/development/lang_go.md
    - python-basic: notes/development/python-basic.md
    - python-install: notes/development/python-install.md
    - python-lambda: notes/development/python-lambda.md
    - python-pypi: notes/development/python-pypi.md
    - python-tips: notes/development/python-tips.md
    - tool-jq: notes/development/tool-jq.md
    - yaml: notes/development/yaml.md

  - Linux:
    - cmd-find: notes/linux/cmd-find.md
    - curl: notes/linux/curl.md
    - firewall-cmd: notes/linux/firewall-cmd.md
    - gnome: notes/linux/gnome.md
    - log_parser: notes/linux/log_parser.md
    - network_knife: notes/linux/network_knife.md
    - openssl: notes/linux/openssl.md
    - shell: notes/linux/shell.md
    - ssh: notes/linux/ssh.md
    - systemd: notes/linux/systemd.md
    - vdo: notes/linux/vdo.md
    - vi: notes/linux/vi.md
    - wsl: notes/linux/wsl.md

  - Observability:
    - graylog: notes/observability/graylog.md
    - netdata: notes/observability/netdata.md
    - prometheus: notes/observability/prometheus.md

  - Tools:
    - Wireshark: notes/tools/wireshark.md

  - References: notes/references.md