apiVersion: batch/v1
kind: Job
metadata:
  name: ocp-oci-sample
spec:
  template:
    spec:
      containers:
      - name: ocp-oci-sample
        image: quay.io/mrbraga/ocp-oci-sample:latest
      restartPolicy: Never
  backoffLimit: 4
