{
 "title": "OpenShift",
 "time": { "from": "2023-10-17T14:20:27.696Z", "to": "2023-10-17T15:44:13.208Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node Name",
    "query": {
     "query": "label_values(node_cpu_info,instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate,namespace)"
    }
   },
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "node_group", "query": ".*master.*, .*worker.*" }
  ]
 },
 "panels": [
  { "title": "header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Count By node (Control Planes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_info{instance=~\".*master.*\"})  by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Total By node (Control Planes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{node=~\".*master.*\"}) by (node) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "api-kas-request-duration-p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(resource_verb:apiserver_request_duration_seconds_bucket:rate:5m{apiserver=\"kube-apiserver\"}) by (verb, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd-request-duration-p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, operation:etcd_request_duration_seconds_bucket:rate5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd disk fsync (WAL | DB) p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\", pod=~\"etcd-$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}-WAL"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\", pod=~\"etcd-$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}-DB"
    }
   ]
  },
  {
   "title": "node-cpu-saturation-load1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"} / scalar(count(instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"})))  != 0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(node_cpu_info{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "node-memory-saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate1m{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cluster-storage-throughput (by namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\", namespace!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", id!=\"\", cluster=\"\", namespace!=\"\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node-disk-saturation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "( instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"} / scalar(count(instance_device:node_disk_io_time_weighted_seconds:rate1m{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"}))) != 0",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "etcd-peer-round-trip-time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (rate(etcd_network_peer_round_trip_time_seconds_bucket{job=\"etcd\", pod=~\"etcd-$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster-cpu-usage (by namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "cluster-memory-usage-wo-cache (by namespace and Node Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", container!=\"\", namespace=~\"$namespace\", node=~\".*master.*\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", container!=\"\", namespace=~\"$namespace\", node=~\".*master.*\"}) by (node)",
     "legendFormat": "Total-Node_{{node}}"
    }
   ]
  },
  {
   "title": "cluster-storage-iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", id!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=\"\", namespace!=\"\", namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", id!=\"\", cluster=\"\", namespace!=\"\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node-network-saturation RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate1m{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{instance}}_tx"
    },
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate1m{job=\"node-exporter\", cluster=\"\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{instance}}_rx"
    }
   ]
  },
  {
   "title": "etcd-total-leader-elections-day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"etcd\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Endpoint Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "changes(kube_endpoint_address_available{endpoint=~\"api.*\"}[5m])",
     "legendFormat": "{{namespace}}_{{ endpoint }}"
    }
   ]
  },
  {
   "title": "node network bytes total (RX/TX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}}_{{device}}_tx"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}}_{{device}}_rx"
    }
   ]
  },
  {
   "title": "node network packets total (RX/TX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_packets_total{instance=~\"$instance\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}}_{{device}}_tx"
    },
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"$instance\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}}_{{device}}_rx"
    }
   ]
  },
  {
   "title": "etcd disk fsync (WAL | DB) p50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\", pod=~\"etcd-$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}-WAL"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\", pod=~\"etcd-$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}-DB"
    }
   ]
  },
  {
   "title": "Total Namespaces by Phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods (by Phase)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}