---
- name: Setup OPCT Cluster Tests - Setup test label 
  hosts: localhost
  gather_facts: yes

  vars:
    installer_path: "{{ installer_path | d(ansible_env.HOME + '/.ansible/okd-installer') }}"
    cluster_path: "{{ installer_path }}/clusters"
    kubeconfig: "{{ cluster_path }}/{{ cluster_name }}/auth/kubeconfig"
  
  tasks:
  - name: Getting all nodes
    register: all_nodes
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Node
      label_selectors:
        - "node-role.kubernetes.io/worker"

  - name: Show all nodes
    debug:
      var: all_nodes
    when: debug | d(false)

  - name: Getting the first worker node
    set_fact:
      node_name: "{{ all_nodes.resources[0].metadata.name }}"
    when: all_nodes.resources | length > 0

  - name: Set the node label
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    when: all_nodes.resources | length > 0
    kubernetes.core.k8s:
      state: patched
      api_version: v1
      kind: Node
      name: "{{ node_name }}"
      definition:
        metadata:
          labels:
            "node-role.kubernetes.io/tests": ''
        spec:
          taints:
            - effect: NoSchedule
              key: "node-role.kubernetes.io/tests"
