# FROM golang:1.17-buster as builder
FROM golang:1.18-alpine as builder

LABEL labs.mtulio.source="https://github.com/mtulio/mtulio.labs/tree/master/labs/aws-random/echo-aws-caller-id"

COPY *.go $GOPATH/src/github.com/mtulio/mtulio.net/
WORKDIR $GOPATH/src/github.com/mtulio/mtulio.net/

RUN go mod init \
    && go get -d -v \
    && go build -ldflags="-s -w" -o echo-aws-get-caller-id

FROM alpine:3.14
COPY --from=builder \
    /go/src/github.com/mtulio/mtulio.net/echo-aws-get-caller-id \
    /usr/bin/
CMD ["/usr/bin/echo-aws-get-caller-id"]
