AWSTemplateFormatVersion: 2010-09-09
Description: Template for Best Practice VPC with 1-3 AZs

Parameters:
  VpcId:
    Description: VPC ID to associate the Carrier Gateway.
    Type: String
    AllowedPattern: ^(?:(?:vpc)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: VPC ID must be with valid name, starting with vpc-.*.
  NamePrefix:
    Description: Cluster Name or Prefix name to prepend the tag Name for each subnet.
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: ClusterName parameter must be specified.
  TransitGatewayId:
    Description: Cluster Name or Prefix name to prepend the tag Name for each subnet.
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: ClusterName parameter must be specified.
  # TODO support more than one subnet
  SubnetIds:
    Description: Cluster Name or Prefix name to prepend the tag Name for each subnet.
    #Type: "List<AWS::EC2::Subnet::Id>"
    Type: CommaDelimitedList
    #AllowedPattern: ".+"
    #ConstraintDescription: ClusterName parameter must be specified.

Resources:
  Gateway:
    Type: "AWS::EC2::TransitGatewayAttachment"
    Properties:
      Options:
        DnsSupport: enable
      SubnetIds: !Ref 'SubnetIds'
      TransitGatewayId: !Ref 'TransitGatewayId'
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref NamePrefix, "tgwa"]]

Outputs:
  TransitGatewayAttachmentId:
    Description: Subnet IDs of the public subnets.
    Value: !Ref Gateway