AWSTemplateFormatVersion: 2010-09-09
Description: Template for Best Practice VPC with 1-3 AZs

Parameters:
  PublicSubnetId:
    #Description: VPC ID to associate the Carrier Gateway.
    Type: String
    #AllowedPattern: ^(?:(?:vpc)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    #ConstraintDescription: VPC ID must be with valid name, starting with vpc-.*.
  NamePrefix:
    Description: Cluster Name or Prefix name to prepend the tag Name for each subnet.
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: ClusterName parameter must be specified.
  DefaultRouteTableId:
    Description: Cluster Name or Prefix name to prepend the tag Name for each subnet.
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: ClusterName parameter must be specified.

Resources:
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref NamePrefix, "eip-natgw"]]

  Gateway:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId:
        "Fn::GetAtt":
        - ElasticIP
        - AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref NamePrefix, "natgw"]]

  Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId:
        Ref: DefaultRouteTableId
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: Gateway

Outputs:
  NatGatewayId:
    Description: ID of the new VPC.
    Value: !Ref Gateway