AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Proxy Cluster with custom VPC PrivateLink Service.

Parameters:
  NamePrefix:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 16
    MinLength: 1
    ConstraintDescription: Cluster name must be alphanumeric, start with a letter, and have a maximum of 27 characters.
    Description: A short, representative cluster name to use for host names and other identifying names.
    Type: String

  TemplatesBaseURL:
    Type: String
    Description: Choose 2 Subnets to create Load balancer and ASG

  VpcId:
    Description: VPC ID to associate the Carrier Gateway.
    Type: String
    AllowedPattern: ^(?:(?:vpc)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: VPC ID must be with valid name, starting with vpc-.*.

  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-4]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-24.
    Default: 10.0.0.0/16
    Description: CIDR block for VPC.
    Type: String

  AmiId:
    Description: AMI ID to provision the EC2.
    Type: String
    AllowedPattern: ^(?:(?:ami)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: Subnet ID must be with valid name, starting with ami-.*.

  SubnetId:
    Description: Base64 user data to provision the EC2.
    Type: String

  SubnetIds:
    Description: Base64 user data to provision the EC2.
    Type: "List<String>"
    #Default: ""

  InstanceType:
    Default: "m6i.large"
    Description: Base64 user data to provision the EC2.
    Type: String

  KeyName:
    Default: "openshift-dev"
    Description: Base64 user data to provision the EC2.
    Type: String

  UserData:
    Description: Base64 user data to provision the EC2.
    Type: String

  IsPublic:
    Description: Base64 user data to provision the EC2.
    Type: String
    Default: "False"
    AllowedValues: ["True", "False"]

  Ipv6AddressCount:
    Description: Base64 user data to provision the EC2.
    Type: String
    Default: "0"

Resources:

  ProxyIamRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "00_iam_role.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        NameSuffix: "proxy"
        CustomPolicyArns: !Join ["-", [!Ref IamPolicy]]

  ProxySecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "01_vpc_99_security_group.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        DescriptionSuffix: "OpenShift Cluster Proxy"
        AllowedProxyCidr: !Ref VpcCidr
        VpcId: !Ref VpcId

  ProxyInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "04_ec2_instance.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        AmiId: !Ref AmiId
        SubnetId: !Ref SubnetId
        UserData: !Ref UserData
        IamRoleArn: !GetAtt 'ProxyIamRole.Outputs.IamRoleArn'
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
        SecurityGroupId: !GetAtt 'ProxySecurityGroup.Outputs.SecurityGroupId'
        IsPublic: !Ref IsPublic
        Ipv6AddressCount: !Ref Ipv6AddressCount

  #
  # Launch Template
  #
  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', ["Security Group for ", "sg-proxy-nlb"]]
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: 3128
        ToPort: 3128
        CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
      - IpProtocol: "tcp"
        FromPort: 3128
        ToPort: 3128
        CidrIp: !Ref VpcCidr
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref NamePrefix, !Ref NameSuffix]]
  # 
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckEnabled: Boolean
      HealthCheckIntervalSeconds: 5
      # HealthCheckPath: String
      HealthCheckPort: 3128
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      IpAddressType: ipv4
      # Matcher: 
      #   Matcher
      Name: !Join ["-", [!Ref NamePrefix, "tg-proxy"]]
      Port: 3128
      Protocol: TCP
      # ProtocolVersion: String
      # Tags: 
      #   - Tag
      TargetGroupAttributes: 
        - Key: deregistration_delay.timeout_seconds
          Value: 60
        # - Key: load_balancing.cross_zone.enabled
        #   Value: true
        - Key: target_group_health.unhealthy_state_routing.minimum_healthy_targets.count
          Value: 1
        - Key: deregistration_delay.connection_termination.enabled
          Value: true
        # - Key: preserve_client_ip.enabled
        #   Value: true
        - Key: target_health_state.unhealthy.connection_termination.enabled
          Value: true
      Targets: []
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      LoadBalancerAttributes: 
        # - Key: deletion_protection.enabled
        #   Value: true
        - Key: load_balancing.cross_zone.enabled
          Value: true
        - Key: deletion_protection.enabled
          Value: true
      Name: !Join ["-", [!Ref NamePrefix, "nlb-proxy"]]
      Scheme: internal
      SecurityGroups: 
        - !Ref LBSecurityGroup
      # SubnetMappings: 
      #   - SubnetMapping
      Subnets: !Split [",", !Ref SubnetIds]
      Tags: 
        - Key: Name
          Value: !Join ['', [!Ref NamePrefix, "proxy-nlb"]]
      Type: network

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData: 
        # BlockDeviceMappings: 
        #   - BlockDeviceMapping
        CapacityReservationSpecification: 
          CapacityReservationPreference: open
        CpuOptions: 
          #AmdSevSnp: String
          CoreCount: 2
          ThreadsPerCore: 2
        #CreditSpecification: 
        #  CreditSpecification
        #DisableApiStop: Boolean
        #DisableApiTermination: Boolean
        #EbsOptimized: Boolean
        #ElasticGpuSpecifications: 
        #  - ElasticGpuSpecification
        #ElasticInferenceAccelerators: 
        #  - LaunchTemplateElasticInferenceAccelerator
        #EnclaveOptions: 
        #  EnclaveOptions
        #HibernationOptions: 
        #  HibernationOptions
        IamInstanceProfile: 
          Arn: !Ref InstanceProfileArn
        ImageId: !Ref ImageId
        #InstanceInitiatedShutdownBehavior: String
        #InstanceMarketOptions: 
        #  InstanceMarketOptions
        InstanceRequirements: 
            #AcceleratorCount: 
            #  AcceleratorCount
            #AcceleratorManufacturers: 
            #  - String
            #AcceleratorNames: 
            #  - String
            #AcceleratorTotalMemoryMiB: 
            #  AcceleratorTotalMemoryMiB
            #AcceleratorTypes: 
            #  - String
            AllowedInstanceTypes: 
              - c*.large
              - m5*.large
              - m6*.large
              - t3.*
            #BareMetal: String
            #BaselineEbsBandwidthMbps: 
            #  BaselineEbsBandwidthMbps
            #BurstablePerformance: String
            #CpuManufacturers: 
            #  - String
            # ExcludedInstanceTypes: 
            #   - String
            #InstanceGenerations: 
            #  - String
            #LocalStorage: String
            #LocalStorageTypes: 
            #  - String
            # MemoryGiBPerVCpu: 
            #   Max: 8
            #   Min: 1
            #MemoryMiB: 
            #  Max: 8
            #  Min: 1
            #NetworkBandwidthGbps: 
            #  NetworkBandwidthGbps
            #NetworkInterfaceCount: 
            #  NetworkInterfaceCount
            #OnDemandMaxPricePercentageOverLowestPrice: 999999
            #RequireHibernateSupport: Boolean
            SpotMaxPricePercentageOverLowestPrice: 50
            #TotalLocalStorageGB: 
            #  TotalLocalStorageGB
            VCpuCount: 
              Max: 4
              Min: 1
        #InstanceType: String
        #KernelId: String
        KeyName: !Ref KeyName
        #LicenseSpecifications: 
        #  - LicenseSpecification
        MaintenanceOptions: 
          AutoRecovery: default
          RebootMigration: True
        # MetadataOptions: 
        #   HttpEndpoint: String
        #   HttpProtocolIpv6: String
        #   HttpPutResponseHopLimit: Integer
        #   HttpTokens: String
        #   InstanceMetadataTags: String
        Monitoring: 
          Enabled: True
        # NetworkInterfaces: 
        #   - NetworkInterface
        # Placement: 
        #   Placement
        PrivateDnsNameOptions: 
          # EnableResourceNameDnsAAAARecord: Boolean
          EnableResourceNameDnsARecord: True
          HostnameType: ip-name
        # RamDiskId: String
        SecurityGroupIds: 
          - !Ref SecurityGroup
        # SecurityGroups: 
        #   - String
        # TagSpecifications: 
        #   - TagSpecification
        UserData: !Ref UserData
      LaunchTemplateName: !Join ["-", [!Ref NamePrefix, "template-proxy"]]
      # TagSpecifications: 
      #   - LaunchTemplateTagSpecification
      # VersionDescription: "String"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Join ["-", [!Ref NamePrefix, "proxy-asg"]]
      # AvailabilityZones: 
      #   - String
      CapacityRebalance: True
      # Context: String
      # Cooldown: String
      DefaultInstanceWarmup: Integer
      DesiredCapacity: 1
      DesiredCapacityType: units
      HealthCheckGracePeriod: 5
      HealthCheckType: EC2,ELB
      # InstanceId: !Ref InstanceId
      InstanceId: !GetAtt 'ProxyInstance.Outputs.InstanceId'
      InstanceMaintenancePolicy: 
        #MaxHealthyPercentage: Integer
        MinHealthyPercentage: 1
      #LaunchConfigurationName: String
      LaunchTemplate: 
        LaunchTemplateName: !Join ["-", [!Ref NamePrefix, "template-proxy"]]
        Version: "$Latest"
      # LifecycleHookSpecificationList: 
      #   - LifecycleHookSpecification
      # LoadBalancerNames: 
      #   - String
      # Recycle the instance weekly

      MetricsCollection: 
        - Granularity: 1Minute
          # Metrics: 
          # - String
      MaxSize: 5
      MinSize: 1
      MaxInstanceLifetime: 604800
      MixedInstancesPolicy: 
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-instancesdistribution.html
        InstancesDistribution: 
          OnDemandAllocationStrategy: lowest-price
          OnDemandBaseCapacity: 1
          #OnDemandPercentageAboveBaseCapacity: Integer
          SpotAllocationStrategy: price-capacity-optimized
          #SpotInstancePools: Integer
          #SpotMaxPrice: String
        # LaunchTemplate: 
        #   LaunchTemplate
      #NewInstancesProtectedFromScaleIn: Boolean
      #NotificationConfigurations: 
      #  - NotificationConfiguration
      #PlacementGroup: String
      #ServiceLinkedRoleARN: String
      Tags: 
      - Key: Name
        Value: !Join ['', [!Ref NamePrefix, "proxy-asg"]]
      TargetGroupARNs: 
        - !Ref TargetGroup
      TerminationPolicies: 
        - OldestLaunchTemplate
        - OldestInstance
        - ClosestToNextInstanceHour
      VPCZoneIdentifier: !Split [",", !Ref SubnetIds]

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html
  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: String
      PolicyType: StepScaling
      #ResourceId: String
      #ScalableDimension: String
      #ScalingTargetId: String
      #ServiceNamespace: String
      StepScalingPolicyConfiguration: 
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 60
        MetricAggregationType: Average
        #MinAdjustmentMagnitude: Integer
        StepAdjustments: 
          - MetricIntervalLowerBound: 50
            MetricIntervalUpperBound: 65
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 66
            MetricIntervalUpperBound: 80
            ScalingAdjustment: 3
      TargetTrackingScalingPolicyConfiguration: 
        #CustomizedMetricSpecification: 
        #  CustomizedMetricSpecification
        DisableScaleIn: False
        PredefinedMetricSpecification: 
          PredefinedMetricType: ALBRequestCountPerTarget
          #ResourceLabel: String
        ScaleInCooldown: 60
        ScaleOutCooldown: 120
        TargetValue: 1000

Outputs:
  ProxyInstanceId:
    Description: Proxy Instance ID.
    Value: !GetAtt 'ProxyInstance.Outputs.InstanceId'
  ProxyPrivateIp:
    Description: Proxy Private IP.
    Value: !GetAtt 'ProxyInstance.Outputs.PrivateIp'