AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack for the EC2 Proxy.
Parameters:
  VpcId:
    Description: VPC ID to associate the Carrier Gateway.
    Type: String
    AllowedPattern: ^(?:(?:vpc)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: VPC ID must be with valid name, starting with vpc-.*.

  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-4]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-24.
    Default: 10.0.0.0/16
    Description: CIDR block for VPC.
    Type: String

  NamePrefix:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 16
    MinLength: 1
    ConstraintDescription: Cluster name must be alphanumeric, start with a letter, and have a maximum of 27 characters.
    Description: A short, representative cluster name to use for host names and other identifying names.
    Type: String

  TemplatesBaseURL:
    Type: String
    Description: Base S3 URL to prepend to the CloudFormation Template URL.

  AmiId:
    Description: AMI ID to provision the EC2.
    Type: String
    AllowedPattern: ^(?:(?:ami)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: Subnet ID must be with valid name, starting with ami-.*.

  SubnetId:
    Description: Subnet ID to provision the EC2.
    Type: String
    AllowedPattern: ^(?:(?:subnet)(?:-[a-zA-Z0-9]+)?\b|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$
    ConstraintDescription: Subnet ID must be with valid name, starting with subnet-.*.

  UserData:
    Description: Base64 user data to provision the EC2.
    Type: String

Resources:
  IAMRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "00_iam_role.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        NameSuffix: "proxy"

  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "01_vpc_99_security_group.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        DescriptionSuffix: "OpenShift Cluster Proxy"
        AllowedProxyCidr: !Ref VpcCidr
        VpcId: !Ref VpcId

  ProxyInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', [!Ref TemplatesBaseURL, "04_ec2_instance.yaml"]]
      TimeoutInMinutes: 5
      Parameters:
        NamePrefix: !Ref NamePrefix
        AmiId: !Ref AmiId
        SubnetId: !Ref SubnetId
        UserData: !Ref UserData
        IamRoleArn: !GetAtt 'IAMRole.Outputs.IamRoleArn'
        KeyName: "openshift-dev"
        InstanceType: "m5.large"
        SecurityGroupId: !GetAtt 'SecurityGroup.Outputs.SecurityGroupId'
        IsPublic: false
        Ipv6AddressCount: 1

Outputs:
  ProxyInstanceId:
    Value: !GetAtt 'ProxyInstance.Outputs.InstanceId'
  ProxyPrivateIp:
    Value: !GetAtt 'ProxyInstance.Outputs.PrivateIp'