apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: lab-scaling
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      # nodeSelector:
      #   lab-scaling-test: "true"
      # tolerations: 
      # - key: "lab-scaling-test"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"