---
- name: OpenShift Install Config Generator
  hosts: localhost
  connection: local

  vars_prompt:
    - name: install_dir
      prompt: What is the Installation Directory?
      private: no
    - name: name
      prompt: What is the cluster name?
      private: no

  vars_files:
    - vars/openshift.yaml

  roles:
    - installer-config
