---
- name: OpenShift Config Load
  hosts: localhost
  connection: local

  vars_prompt:
    - name: install_dir
      prompt: What is the Installation Directory?
      private: no

  tasks:
    - name: OpenShift Config Load | Get Installer Meta
      set_fact:
          ocp_installer_state: "{{ lookup('file', install_dir + '/.openshift_install_state.json') }}"
          ocp_installer_metadata: "{{ lookup('file', install_dir + '/metadata.json') }}"
      no_log: yes

    - name: OpenShift Config Load | Set Defaults
      set_fact:
          ocp_install_image: "{{ ocp_installer_state[\"*rhcos.Image\"] }}"
          ocp_install_infraID: "{{ ocp_installer_metadata.infraID }}"
          ocp_config_baseDomain: "{{ ocp_installer_state[\"*installconfig.InstallConfig\"][\"config\"][\"baseDomain\"] }}"
          ocp_cluster_tags: {}

    - name: OpenShift Config Load | Set Default tags
      set_fact:
          ocp_cluster_tags: "{% set x=ocp_cluster_tags.__setitem__('kubernetes.io/cluster/'+ocp_install_infraID, 'owned' ) %}{{ ocp_cluster_tags }}"

    - name: OpenShift Config Load | Set Default Resource Names
      set_fact:
          bootstrap_iam_role_name: "{{ ocp_install_infraID }}-instance-bootstrap"
          controlplane_iam_role_name: "{{ ocp_install_infraID }}-instance-controlplane"
          compute_iam_role_name: "{{ ocp_install_infraID }}-instance-compute"

    - name: Create Runtime config
      set_fact:
        cluster_state: "{{ lookup('file', install_dir + '/cluster_state.json', errors='ignore') }}"
    - set_fact:
        cluster_state:
          tags: "{{ ocp_cluster_tags }}"
          zones:
            base: "{{ ocp_config_baseDomain }}"
            base_id: ''
            cluster: "{{ ocp_install_infraID }}.{{ ocp_config_baseDomain }}"
            cluster_id: ''
          infra_id: "{{ ocp_install_infraID }}"
          network:
            vpc_id: ''
          loadbalancers: {}
      when: cluster_state | length <= 0

    - debug: var=ocp_install_image
    - debug: var=ocp_install_infraID
