---
- include: openshift_config_load.yaml

- name: OpenShift Create Node
  hosts: localhost
  connection: local

  pre_tasks:
    - include_vars: "vars/compute/{{ name }}-{{ provider }}.yaml"

  roles:
    - role: mtulio.cloud-compute

- include: openshift_config_dump.yaml
