---
- name: OpenShift | dump state to file
  hosts: localhost
  connection: local

  tasks:
    - name: Show Current Config
      debug:
        var: cluster_state

    - copy:
        dest: "{{ install_dir }}/cluster_state.json"
        content: "{{ cluster_state }}"
