---
- hosts: localhost
  connection: local

  vars:
    cidr_block: 10.0.0.0/16
    region: us-east-1
    ami_id: fedora_34_1_x64_20G_alibase_20211028.vhd
    instance_type: ecs.t6-c2m1.large

  tasks:
    - name: Create VPC
      ali_vpc:
        cidr_block: '{{ cidr_block }}'
        vpc_name: new_vpc
        alicloud_region: "{{ region }}"
      register: created_vpc

    - debug: var=created_vpc

    - name: Create VSwitch
      ali_vswitch:
        alicloud_zone: '{{ region }}'
        cidr_block: '{{ cidr_block  }}'
        vswitch_name: new_vswitch
        vpc_id: '{{ created_vpc.vpc.id |d(omit) }}'
        alicloud_region: "{{ region }}"
      register: created_vsw
      check_mode: no

    - debug: var=created_vsw

    - name: Create security group
      ali_security_group:
        name: new_group
        vpc_id: '{{ created_vpc.vpc.id }}'
        alicloud_region: "{{ region }}"
        rules:
          - ip_protocol: tcp
            port_range: 22/22
            source_cidr_ip: 0.0.0.0/0
            priority: 1
          - ip_protocol: tcp
            port_range: 80/80
            source_cidr_ip: 0.0.0.0/0
            priority: 1
        rules_egress: []
      register: created_group
      check_mode: no

    - name: Create a set of instances
      ali_instance:
         security_groups: '{{ created_group.group_id |d(omit) }}'
         instance_type: "{{ instance_type }}"
         alicloud_region: "{{ region }}"
         image_id: "{{ ami_id }}"
         instance_name: "My-new-instance"
         instance_tags:
             Name: lb-app
             Version: 0.0.1
         count: 1
         count_tag:
             Name: lb-app
         allocate_public_ip: true
         max_bandwidth_out: 50
         vswitch_id: '{{ created_vsw.vswitch.id}}'
      register: create_instance
