---

- name: Target Group | AWS | Register EC2 | machine spec
  debug:
    var: machine

- name: Target Group | AWS | Register EC2 | Filter target machines
  ec2_instance_info:
    filters: "{{ machine.filters }}"
  register: ec2_out

- name: Target Group | AWS | Register EC2 | ec2 filter spec
  debug:
    var: ec2_out

- name: Target Group | AWS | Register EC2 | ec2 filter check
  debug:
    msg: "The filters provided did not returned any instance. Fix it and try again. Filter={{ machine.filters }}"
  failed_when: ec2_out.instances | length == 0

- name: Target Group | AWS | Register EC2 | Extract instance IP
  set_fact:
    machine_target_id: "{{ ec2_out.instances[0].private_ip_address }}"
  when: machine.resource_type == 'ip'

- name: Target Group | AWS | Register EC2 | Extract instance ID
  set_fact:
    machine_target_id: "{{ ec2_out.instances[0].instance_id }}"
  when: machine.resource_type == 'instanceId'

- name: Target Group | AWS | Register EC2 | Attach instance to target group
  community.aws.elb_target:
    target_group_name: "{{ tg_out.target_group_name }}"
    target_id: "{{ machine_target_id }}"
    target_port: "{{ machine.port | d(omit) }}"
    state: present
