---

- name: DNS | AWS | Zone config start
  debug:
    var: zone

- name: DNS | AWS | Get VPC by Name
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ zone.vpc_name }}"
  when: zone.vpc_name is defined
  register: vpc_info

- name: DNS | AWS | VPC Info
  debug:
    var: vpc_info

- name: DNS | AWS | Set VPC Id on zone
  set_fact:
    zone: "{{ zone | combine ({ 'vpc_id' : vpc_info.vpcs[0].vpc_id }) }}"
  when:
    - zone.vpc_name is defined
    - vpc_info.vpcs|length > 0

- name: DNS | AWS | Create cluster zone
  community.aws.route53_zone:
    zone: "{{ zone.zone }}"
    vpc_id: "{{ zone.vpc_id | d(vpc_info.vpcs[0].vpc_id) }}"
    vpc_region: "{{ zone.vpc_region }}"
    comment: "{{ zone.comment | d(omit) }}"
    state: present
  when: (zone.openshift_type is defined) and zone.openshift_type == 'cluster'
  register: z_out

- name: DNS | AWS | Zone Info
  debug:
    var: z_out

#- set_fact:
#    cluster_state: "{% set x=cluster_state.zones.__setitem__(zone.openshift_type+'_id', z_out.zone_id) %}{{ cluster_state }}"
#  when: zone.openshift_type is defined
