---
# Main variables.
# TODO: should be define an instandard, maybe same used on installer_config role
ocp_config_baseDomain: "'{{ lookup('ansible.builtin.env', 'CONFIG_BASE_DOMAIN') }}'"
ocp_config_name: "'{{ lookup('ansible.builtin.env', 'CONFIG_CLUSTER_NAME') }}'"
ocp_config_region: "{{ lookup('ansible.builtin.env', 'CONFIG_REGION') }}"
#ocp_config_pullSecret_file: "{{ lookup('env', 'CONFIG_PULL_SECRET_FILE') }}"
ocp_config_sshKey: "{{ lookup('ansible.builtin.env', 'CONFIG_SSH_KEY') }}"
#ocp_config_bucket: "{{ lookup('env', 'CONFIG_BUCKET') }}"
ocp_config_provider: "{{ lookup('ansible.builtin.env', 'CONFIG_PROVIDER') }}"

provider: "{{ ocp_config_provider }}"
region: "{{ ocp_config_region }}"

# Feed the installer_config role variables
config_baseDomain: "{{ ocp_config_baseDomain }}"
config_metadata_name: "{{ ocp_config_name }}"
config_networking: yes

config_platform:
  aws:
    region: "{{ ocp_config_region }}"

config_pullSecret_file: "{{ lookup('env', 'CONFIG_PULL_SECRET_FILE') }}"
config_sshKey: "{{ ocp_config_sshKey }}"
